name: SonarCloud Analysis

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Cache SonarCloud scanner
      - name: Cache SonarCloud Scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/scanner
          key: ${{ runner.os }}-sonar-scanner

      - name: Install SonarScanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

      - name: Install coverlet
        shell: powershell
        run: |
          dotnet tool install --global coverlet.console
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
      - name: Build, Test and Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./ACleanAPI
        shell: powershell
        run: |
          # --- Start SonarCloud Analysis ---
          ${{ runner.temp }}\scanner\dotnet-sonarscanner begin `
            /k:"johnnybehague_ACleanAPI" `
            /o:"johnnybehague" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" `
            /d:sonar.coverageReportPaths="**/TestResults/coverage.cobertura.xml"
      
          # --- Run tests with coverage ---
          dotnet test --logger "trx" `
            /p:CollectCoverage=true `
            /p:CoverletOutput=TestResults/coverage `
            /p:CoverletOutputFormat=cobertura
      
          # Debug : check files
          Get-ChildItem -Recurse -Filter "*.cobertura.xml"
      
          # --- End SonarCloud Analysis ---
          ${{ runner.temp }}\scanner\dotnet-sonarscanner end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
